"""first init

Revision ID: 2a43d2273dfc
Revises: 0de70ae9f579
Create Date: 2023-06-12 15:22:47.541998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a43d2273dfc'
down_revision = '0de70ae9f579'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
