"""updated

Revision ID: c88a065f94d5
Revises: 2a43d2273dfc
Create Date: 2023-06-12 15:27:30.299353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c88a065f94d5'
down_revision = '2a43d2273dfc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
