"""updated

Revision ID: d7c656ec2d0c
Revises: c88a065f94d5
Create Date: 2023-06-12 15:52:53.393799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7c656ec2d0c'
down_revision = 'c88a065f94d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
