"""updated

Revision ID: d87b3c0a2b20
Revises: d7c656ec2d0c
Create Date: 2023-06-12 16:02:12.422848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd87b3c0a2b20'
down_revision = 'd7c656ec2d0c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
